global:
  scrape_interval: "15s"
  # scrape_interval: "1m"

scrape_configs:
  - job_name: "nestjs"
    metrics_path: "/api/metrics"  
    static_configs:
      - targets:
          - "host.docker.internal:7000"

  - job_name: "node"
    static_configs:
      - targets:
          - "host.docker.internal:9100"
